name = "FeedoBridge"
client_id = "9da46159e4de788dab1f3cc2533551e4"
application_url = "https://shopifyapp.xmasforest.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://shopifyapp.xmasforest.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[app_proxy]
url = "https://shopifyapp.xmasforest.com/proxy"
subpath = "feedobridge"
prefix = "apps"

[[extensions]]
type = "theme"
name = "FeedoBridge Theme Extension"
handle = "feedobridge-theme-extension"

